name: Amazon Price Tracker

on:
  schedule:
    - cron: '0 14 * * *'   # Runs every day at 14:00 UTC
  workflow_dispatch:

jobs:
  track-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore price cache
        uses: actions/cache@v3
        with:
          path: last_price_*.txt
          key: last-price-cache

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run price tracker script
        env:
          ALERT_EMAIL: ${{ secrets.ALERT_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python amazon.py

      - name: Cache price files
        uses: actions/cache@v3
        with:
          path: last_price_*.txt
          key: last-price-cache
