name: Ulta Price Tracker

on:
  schedule:
    - cron: '0 14 * * *'  # Runs daily at 14:00 UTC
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore promo_seen.txt cache
        uses: actions/cache@v3
        with:
          path: promo_seen.txt
          key: promo-flag

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run price tracker script
        env:
          ALERT_EMAIL: ${{ secrets.ALERT_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python ulta_tracker.py
